version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin #Usuario personalizado
      - RABBITMQ_DEFAULT_PASS=admin #Contraseña personalizada